kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:jdk11
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: main
      DB_USERNAME: main
      DB_PASSWORD: main
      JWT_SECRET_KEY: "MDIyZGQwMDdjNDA3ZDQwYTc4MGYyNjdkZjFkZTJkMzRhMDhmMTNkN2QyMWY5ZjMxMTYwZjM5ZDI1YjE5ZjhiYQ=="
    commands:
      - sleep 10 # Wait for PostgreSQL service starting
      - ./gradlew test
      - ./gradlew build

  - name: image
    image: plugins/docker
    settings:
      registry: registry.okami101.io
      repo: registry.okami101.io/adr1enbe4udou1n/spring-boot-realworld
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    depends_on:
      - build

  # - name: deploy
  #   image: appleboy/drone-ssh
  #   settings:
  #     host: front.okami101.io
  #     port: 2222
  #     username: okami
  #     key:
  #       from_secret: swarm_ssh_key
  #     script:
  #       - docker service update --image registry.okami101.io/adr1enbe4udou1n/spring-boot-realworld:latest springbootrealworld_app --with-registry-auth
  #   depends_on:
  #     - image

services:
  - name: db
    image: postgres:14
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main

trigger:
  event:
    - push
    - pull_request
