version: "3"

tasks:
  prepare:
    cmds: []
  install:
    cmds: []
  lint:
    cmds: []
  build:
    cmds:
      - gradle build
      - gradle sonar -Dsonar.projectName="Spring Boot Realworld" -Dsonar.host.url={{.SONAR_URL}} -Dsonar.projectKey={{.SONAR_PROJECT_KEY}} -Dsonar.token={{.SONAR_TOKEN}}
      - gradle test jacocoTestReport sonarqube
  test:
    cmds: []
