version: "3"

tasks:
  prepare:
    cmds: []
  install:
    cmds: []
  lint:
    cmds: []
  build:
    cmds:
      - gradle build -Dsonar.host.url={{.SONAR_URL}} -Dsonar.projectName="Spring Boot Realworld" -Dsonar.projectKey={{.SONAR_PROJECT_KEY}} -Dsonar.token={{.SONAR_TOKEN}} sonar
  test:
    cmds:
      - gradle test jacocoTestReport -Dsonar.host.url={{.SONAR_URL}} -Dsonar.projectName="Spring Boot Realworld" -Dsonar.projectKey={{.SONAR_PROJECT_KEY}} -Dsonar.token={{.SONAR_TOKEN}} sonar
