on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"
      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build
        env:
          DB_HOST: ${{ vars.POSTGRESQL_HOST }}
          DB_PORT: 5432
          DB_DATABASE: conduit_springboot_test
          DB_USERNAME: test
          DB_PASSWORD: test
          JWT_SECRET_KEY: "MDIyZGQwMDdjNDA3ZDQwYTc4MGYyNjdkZjFkZTJkMzRhMDhmMTNkN2QyMWY5ZjMxMTYwZjM5ZDI1YjE5ZjhiYQ=="
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: spring-boot-realworld
        run: ./gradlew build --no-daemon jacocoTestReport sonar
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
