on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ vars.POSTGRESQL_HOST }}
      DB_PORT: 5432
      DB_DATABASE: conduit_springboot_test
      DB_USERNAME: test
      DB_PASSWORD: test
      JWT_SECRET_KEY: "MDIyZGQwMDdjNDA3ZDQwYTc4MGYyNjdkZjFkZTJkMzRhMDhmMTNkN2QyMWY5ZjMxMTYwZjM5ZDI1YjE5ZjhiYQ=="
      SONAR_URL: ${{ vars.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: spring-boot-realworld
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"
      - run: ./gradlew build --no-daemon jacocoTestReport -Dsonar.host.url={{.SONAR_URL}} -Dsonar.projectName="Spring Boot Realworld" -Dsonar.projectKey={{.SONAR_PROJECT_KEY}} -Dsonar.token={{.SONAR_TOKEN}} sonar
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
